### PR TITLE
add style to input and button

### PR DESCRIPTION
**Pull request by glitch-txs**

### CODE REVIEW

**Comment by diego-rapoport** [comment]
Trully liked that button and the box of lists!! Maybe just make the font-size bigger for the todos.

**Review by CJaclyn — COMMENTED** [review]
Love the button! I think you should make a background for each of the list items instead of the whole list so the items are more separated

Screenshot 2023-03-11 135905

**Comment by kingl0w** [comment]
Loving the style so far, looks really good

**Comment by glitch-txs** [comment]
I love that @CJaclyn would you mind commiting that change to this branch?

**Review by diego-rapoport — APPROVED** [review]

**Pull request merged**
