### PR TITLE
Add done and enter key to add

### PR DESCRIPTION
**Pull request by diego-rapoport**
Two new features: done button and add todo on enter

### CODE REVIEW

**Review by CJaclyn — CHANGES_REQUESTED** [review]
I think you accidentally deleted the addToDoBtn variable `let addToDoBtn = document.getElementById('todo-add');` in script.js so the add button doesn't work anymore

**Comment by glitch-txs** [comment]
Seems like there's some merge conflicts, can you `git pull origin main` locally?

**Comment by diego-rapoport** [comment]
> I think you accidentally deleted the addToDoBtn variable `let addToDoBtn = document.getElementById('todo-add');` in script.js so the add button doesn't work anymore

Actually I didn't removed that part and it worked for me. Maybe some debug could shed some light on what went wrong while you tested and I can correct it properly.
Tell me if the problem persists even after I resolve the conflicts.

**Review by CJaclyn — APPROVED** [review]

**Comment by CJaclyn** [comment]
> > I think you accidentally deleted the addToDoBtn variable `let addToDoBtn = document.getElementById('todo-add');` in script.js so the add button doesn't work anymore
> 
> Actually I didn't removed that part and it worked for me. Maybe some debug could shed some light on what went wrong while you tested and I can correct it properly. Tell me if the problem persists even after I resolve the conflicts.

Sorry, that's my bad! The line were hidden on github and had to be expanded for me to see...

**Review by kingl0w — APPROVED** [review]

**Pull request merged**
